# POST  http://127.0.0.1:3000/api/users/register
POST  http://127.0.0.1:3000/api/users/login
# GET   http://127.0.0.1:3000/api/users/current
# POST   http://127.0.0.1:3000/api/lists/add
# DELETE    http://127.0.0.1:3000/api/lists/remove/5e95e0e68173461d78beb1d4
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlOTc2MDY2ZmJlZjZiMDZkMDI1ZDRiZCIsIm5hbWUiOiJ4dSIsImlhdCI6MTU4Njk3ODk3MSwiZXhwIjoxNTg2OTgyNTcxfQ.xxbBRkK6HXAafJD786hBVq0t-_Svgz_wWmc4QP6asvI

{
   "name": "xu",
   "email": "1531883@qq.com",
   "password": "123"
}


# GET http://192.168.0.1/ HTTP/1.1


#REST Client

